# Generated by Django 3.2 on 2023-05-26 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simple_gateway", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssoauthenticated",
            name="sso_token",
        ),
        migrations.RemoveField(
            model_name="ssoauthrequest",
            name="sso_token",
        ),
    ]
