# Generated by Django 3.2 on 2023-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_gateway", "0002_auto_20230526_1450"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssoauthrequest",
            name="next_url",
        ),
        migrations.AddField(
            model_name="ssoauthrequest",
            name="next_path",
            field=models.CharField(
                default="",
                help_text="To go after success auth",
                max_length=512,
                verbose_name="Next path",
            ),
            preserve_default=False,
        ),
    ]
