# Generated by Django 3.2 on 2023-05-26 15:57

from django.db import migrations, models

import simple_gateway.models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_gateway", "0003_auto_20230526_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssoauthenticated",
            name="auth_token",
            field=models.CharField(
                default=simple_gateway.models.token_generator,
                max_length=36,
                unique=True,
                verbose_name="AuthToken",
            ),
        ),
    ]
