# Generated by Django 3.2 on 2023-05-28 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simple_gateway", "0004_ssoauthenticated_auth_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssoauthrequest",
            name="next_path",
        ),
    ]
